### ISSUE TITLE
Instruction build for wahoo

### ISSUE THREAD

**Issue by NgoHuy** [TeamWin/android_device_google_wahoo#5]
Hi team,
I'm trying to build twrp for pixel 2 ( non XL ) with [this guide](https://forum.xda-developers.com/t/how-to-building-twrp-from-source-with-goodies.4029449/).
But the configuration could not find the board. I also see [jenkins](https://jenkins.twrp.me/job/walleye-test/6/consoleFull) and built manually but no luck.
Any instruction or setup guide in details?

Best regards,
Severus

**Comment by bigbiff** [comment]
Go to our buildtrees_manifests project and add the appropriate repos to the tree used in jenkins. Then you should be able to build the device tree.
